build:
    build_starting:
        image: python:2
        commands:
            - echo "Beginning new build"
    run_tests:
        image: python:2-alpine
        commands:
            - pip install -r requirements.txt
            - python testing.py
publish:
    docker:
        repo: brbesset/cicd_demoapp
        tag: latest
        username: brbesset
        password: cisco123
        email: brian.bessette@gmail.com

deploy:
    webhook:
        image: plugins/drone-webhook
        skip_verify: true
        method: POST
        auth:
            username: CICD1
            password: CICD1
        urls:
            - https://control.sandbox.imapex.io/marathon/v2/apps/class/brbesset/restart?force=true

notify:
    spark:
        image: hpreston/drone-spark
        auth_token: NzE0MTBhYTEtYzQ5MS00ZjdkLWI4ZGMtOTUzNDRmM2IwZjU2YTY1MDk5ODctMTNi
        roomId: Y2lzY29zcGFyazovL3VzL1JPT00vODVmMzAzNTAtMTQwNC0xMWU3LTkxZWQtNjMzYWE4Y2FkZDNj
